name: dokit
description: 开发工具集
version: 0.8.1-nullsafety.0
homepage: https://www.dokit.cn/#/index/home


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_format: ^2.0.2
  vm_service: ^6.2.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.5
  image: ^3.0.2
  google_fonts: ^2.0.0
  string_scanner: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2


flutter:
  uses-material-design: true

  assets:
    - images/dokit_ic_close.png
    - images/dk_frame_hist.png
    - images/dk_method_channel.png
    - images/dk_sys_info.png
    - images/dk_view_check.png
    - images/dk_log_info.png
    - images/dk_ram.png
    - images/dk_view_route.png
    - images/dk_net_monitor.png
    - images/dokit_flutter_btn.png
    - images/dk_channel_check_h.png
    - images/dk_channel_check_n.png
    - images/dk_channel_expand_h.png
    - images/dk_channel_expand_n.png
    - images/dk_fps_chart.png
    - images/dk_route_arrow.png
    - images/dk_memory_search.png
    - images/dk_color_pick.png
    - images/dk_source_code.png
    - images/dk_time_counter.png