source 'git@github.com:CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'DoKitSwiftDemo' do
  pod 'DoraemonKit', :subspecs => ['Core'],  :path => '../../../', :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['WithGPS'],  :path => '../../../', :configurations => ['Debug']
  pod 'DoraemonKit', :subspecs => ['WithMLeaksFinder'],  :path => '../../../', :configurations => ['Debug']
  pod 'FBRetainCycleDetector', :git => 'https://github.com/facebook/FBRetainCycleDetector.git', :configurations => ['Debug']
  pod 'AFNetworking'
  
  
end


post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['CODE_SIGN_IDENTITY'] = ''
  end
  
  
end
